version: '2'
services:
  mariadb:
    image: library/mariadb:10.2
    env_file:
      - .env/.mariadb
    volumes:
      - ./conf.d:/etc/mysql/conf.d

  redis:
    image: redis:alpine
    volumes:
      - ./redis.conf:/etc/conf.d/redis.conf
    command: ["redis-server","/etc/conf.d/redis.conf"]

  frappe:
    build: .
    ports:
      - "8000:8000" #webserver_port
      - "9000:9000" #socketio_port
      - "6787:6787" #file_watcher_port
    volumes:
      - ./sites:/home/frappe/frappe-bench/sites
    stdin_open: true
    tty: true
    links:
      - redis
      - mariadb
    depends_on:
      - mariadb
      - redis

  nginx:
    image: library/nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./sites:/sites
    ports:
      - "80:80"
    depends_on:
      - frappe